/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Demo;

import WS3DCoppelia.WS3DCoppelia;
import WS3DCoppelia.util.Constants;
import co.nstant.in.cbor.CborException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public static void main(String[] args) throws CborException, IOException {
        Environment env = new Environment();
        AgentMind a = new AgentMind(env);

        //WS3DCoppelia world = new WS3DCoppelia(4,4);
        //try {
        //    world.startSimulation();
        //} catch (IOException ex) {
        //    Logger.getLogger(Environment.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (CborException ex) {
        //    Logger.getLogger(Environment.class.getName()).log(Level.SEVERE, null, ex);
        //}
        //world.createAgent(3, 3.8f, Constants.Color.AGENT_GREEN);
        //try {
        //    Thread.sleep(30000);
        //} catch (InterruptedException e) {
        //    throw new RuntimeException(e);
        //}
        //world.createAgent(3, 3.2f, Constants.Color.AGENT_GREEN);
        //try {
        //    Thread.sleep(30000);
        //} catch (InterruptedException e) {
        //    throw new RuntimeException(e);
        //}
        //world.createAgent(3, 2.6f, Constants.Color.AGENT_GREEN);
        //try {
        //    Thread.sleep(30000);
        //} catch (InterruptedException e) {
        //    throw new RuntimeException(e);
        //}
        //world.createAgent(3, 2, Constants.Color.AGENT_GREEN);
        //try {
        //    Thread.sleep(30000);
        //} catch (InterruptedException e) {
        //    throw new RuntimeException(e);
        //}
        //world.createAgent(3, 1.4f, Constants.Color.AGENT_GREEN);
        //try {
        //    Thread.sleep(20000);
        //} catch (InterruptedException e) {
        //    throw new RuntimeException(e);
        //}
    }
}
