/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Demo;

import co.nstant.in.cbor.CborException;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws CborException, IOException {
        Environment env = new Environment();
        AgentMind a = new AgentMind(env);
    }
}
